name: 'Create and Publish Docker Image to Harbor Repository'

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
      REPO_NAME:
        required: true
        type: string
      CHART_NAME:
        required: true
        type: string
      CHART_REPO_NAME:
        required: true
        type: string
    secrets:
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true
      github_token:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: rishindra23/build-number@v3
        with:
          token: ${{secrets.github_token}} 
          
      - name: Get Image Tag
        id: get-tag
        run: |
          type='${{ github.ref_type }}';
          RELEASE_VERSION=${{ github.ref_name }};
          if [[ $type = 'branch' ]] 
          then
              RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
          fi
          echo "::set-output name=tag::$RELEASE_VERSION";
        shell: bash
        
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.metabob.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }} 

      - name: Helm and helm-push plugin Install
        run: |
          helm plugin install https://github.com/MetabobProject/helm-push              
          
      - name: Docker image build
        run: |
          docker build -t ${{inputs.APP_NAME}} .  
      
      - name: Get build number
        run: |
          echo Build number is ${{ steps.get-tag.outputs.tag }}
      
      - name: Files and images Cleanup 
        run: |
          docker image prune -a -f 
          docker images
          rm -rf *
