name: 'Create and Publish Docker Image to Harbor Repository'

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
      REPO_NAME:
        required: true
        type: string
      CHART_NAME:
        required: true
        type: string
      CHART_REPO_NAME:
        required: true
        type: string
      REPO_URL:
        required: true
        type: string
    secrets:
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate build number
        uses: MetabobProject/build-number@v3
        with:
          token: ${{secrets.github_token}} 
          
      - name: Get Image Tag
        id: get-tag
        run: |
          type='${{ github.ref_type }}';
          RELEASE_VERSION=${{ github.ref_name }};
          if [[ $type = 'branch' ]] 
          then
              RELEASE_VERSION="$( date -I )-${BUILD_NUMBER}";
          fi
          echo "::set-output name=tag::$RELEASE_VERSION";
        shell: bash
        
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{inputs.REPO_URL}}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }} 

      - name: Helm and helm-push plugin Install
        run: |
          helm plugin install https://github.com/MetabobProject/helm-push              
          
      - name: Docker image build
        run: |
          docker build -t ${{inputs.APP_NAME}} .  
          
      - name: Tag Docker Image and Push to Harbor
        run: |
          docker tag ${{inputs.APP_NAME}} ${{inputs.REPO_URL}}/${{inputs.PROJECT_NAME}}/${{inputs.REPO_NAME}}:${{ steps.get-tag.outputs.tag }}
          docker push ${{inputs.REPO_URL}}/${{inputs.PROJECT_NAME}}/${{inputs.REPO_NAME}}:${{ steps.get-tag.outputs.tag }} 
            
          
      - name: Pull Helm chart from Harbor
        run: |
          helm repo add harbor https://${{inputs.REPO_URL}}/chartrepo/${{inputs.CHART_REPO_NAME}} --username ${{ secrets.HARBOR_USERNAME }}  --password ${{ secrets.HARBOR_PASSWORD }}
          helm pull harbor/${{inputs.CHART_NAME}}
          mkdir -p ${{inputs.CHART_NAME}}
          tar xvfz ${{inputs.CHART_NAME}}-*.tgz ${{inputs.CHART_NAME}}/
          ls -a
          
      - name: Updating Helm Chart Values.yaml file
        uses: MetabobProject/helm-set-image-tag-action@main
        with:
          values_files: ${{inputs.CHART_NAME}}/values-integration.yaml
          tag_keys: .image.tag
          tag_value: ${{ steps.get-tag.outputs.tag }}
          
          
      - name: Updating Helm chart.yaml file
        uses: MetabobProject/helm-set-image-tag-action@main
        with:
          values_files: ${{inputs.CHART_NAME}}/Chart.yaml
          tag_keys: .version,.appVersion
          tag_value: ${{ steps.get-tag.outputs.tag }}
          
          
      - name: Pushing Updated helm chart in Harbor
        run: |
          ls -a
          tar -zcvf ${{inputs.CHART_NAME}}.tar.gz ${{inputs.CHART_NAME}}
          helm cm-push -f ${{inputs.CHART_NAME}}.tar.gz https://${{inputs.REPO_URL}}/chartrepo/${{inputs.PROJECT_NAME}} --username ${{ secrets.HARBOR_USERNAME }}  --password ${{ secrets.HARBOR_PASSWORD }}
        
      - name: Files and images Cleanup 
        run: |
          docker image prune -a -f 
          docker images
          rm -rf *
